const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST';
const JOIN_EVENT_REQUEST = 'JOIN_EVENT_REQUEST';
const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';

export { CREATE_EVENT_REQUEST, CREATE_EVENT_SUCCESS, JOIN_EVENT_REQUEST };
