const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
const SEARCH_WITH_DESCRIPTION = 'SEARCH_WITH_DESCRIPTION';
const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';

export { GET_ORDER_REQUEST, GET_ORDER_SUCCESS, SEARCH_WITH_DESCRIPTION };
