const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
const SEARCH_WITH_DESCRIPTION = 'SEARCH_WITH_DESCRIPTION';
const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
const CHANGE_ORDER_STATUS = 'CHANGE_ORDER_STATUS';
const CANCEL_ORDER = 'CANCEL_ORDER';

export {
  GET_ORDER_REQUEST,
  GET_ORDER_SUCCESS,
  SEARCH_WITH_DESCRIPTION,
  CHANGE_ORDER_STATUS,
  CANCEL_ORDER,
};
