const SHOW_TOAST = 'SHOW_TOAST';
const HIDE_TOAST = 'HIDE_TOAST';
const SET_TOAST_MASSAGE = 'SET_TOAST_MASSAGE';
const SET_TOAST_TYPE = 'SET_TOAST_TYPE';

export { SHOW_TOAST, HIDE_TOAST, SET_TOAST_MASSAGE };
